"""
ceiling.py -- computed numbers and the figure for `channel_note.tex`.

Three things, all derived, none transcribed:

1. The **balance ceiling** of NWAY.md 7.7 for the three illustrative regional splits of the
   $6.2B footprint, at k = 4..10.  Computed by calling `td.channel
   .allocate_districts` itself, so the note and the implementation cannot drift apart.
2. The **saturation arithmetic** of NWAY.md 7.2 -- how much of a zip's utility is
   opportunity and how much is the incumbency premium, at theta = 0.40, lam = 0.30 and a
   5% saturation.
3. A tiny **2x2 staffing example** where the Nash matching and the utilitarian matching
   disagree, used in the note's stage-2 section.

Everything lands in `ceiling_numbers.tex` as LaTeX macros and in `figures/ceiling.png`.
Run from anywhere; paths resolve relative to this file.

The regional splits are *illustrative* (NWAY.md 7.7 says so explicitly): real regional
opportunity totals are the outstanding input.  Only the aggregate ($6.2B) and the component
count (4) are instance facts.
"""
from __future__ import annotations

import itertools
import math
import pathlib
import sys

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parent.parent                      # docs/channel_note -> docs -> repo root
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from td import channel  # noqa: E402

# The house figure style lived in `code/gfx/style.py`, which did not survive the 2026-08-31
# prune.  Only these four values were used, so they are inlined and the note stays
# self-contained -- it builds with nothing but the package and matplotlib.
PALETTE = {"A": "#2166ac", "B": "#b2182b", "neutral": "#4d4d4d"}
RC = {"font.size": 8, "axes.titlesize": 8, "axes.labelsize": 8,
      "xtick.labelsize": 6, "ytick.labelsize": 6, "legend.fontsize": 7,
      "axes.spines.top": False, "axes.spines.right": False,
      "xtick.direction": "out", "ytick.direction": "out",
      "figure.titlesize": 10, "savefig.dpi": 200}

# ------------------------------------------------------------------ the instance
TOTAL_B = 6.2          # $B of opportunity across the footprint (NWAY.md 7.6)
N_ZIPS = 2232          # zips carrying sales
N_REPS = 72            # distinct reps including the "open" vacancy key
TARGET_B = 1.0         # the ~$1B territory target

# illustrative regional splits, in $B: west coast / east coast / Texas / Florida
SPLITS = {
    "even": ("even-ish", {"W": 2.0, "E": 2.2, "TX": 1.1, "FL": 0.9}),
    "east": ("east-heavy", {"W": 1.6, "E": 3.0, "TX": 0.9, "FL": 0.7}),
    "coast": ("coast-heavy", {"W": 2.6, "E": 2.6, "TX": 0.6, "FL": 0.4}),
}
KS = list(range(4, 11))
KS_TABLE = [6, 7, 8]

THETA, LAM = 0.40, 0.30
SATURATION = 0.05      # t_z = T_z / M_z, "~5%" (NWAY.md 7.2)

WORD = {4: "Four", 5: "Five", 6: "Six", 7: "Seven", 8: "Eight", 9: "Nine", 10: "Ten"}


def ceiling(comps: dict, k: int) -> dict:
    """The ceiling for one split at one k, straight from the implementation."""
    return channel.allocate_districts({c: m * 1e9 for c, m in comps.items()}, k)


def min_spread_budget(comps: dict, k: int):
    """The district budget minimising the ceiling spread, by brute force over all budgets.

    The note needs this because `allocate_districts` reports the spread *at* the budget
    maximising `sum_c k_c log(M_c/k_c)`, and that budget is not always the one with the
    smallest ceiling spread -- an honest caveat on the table, and a distinction the
    proposition in the note has to make.
    """
    names = sorted(comps)
    total = sum(comps.values())
    mean = total / k
    best = None
    for alloc in itertools.product(range(1, k + 1), repeat=len(names)):
        if sum(alloc) != k:
            continue
        sizes = [comps[n] / kc for n, kc in zip(names, alloc) for _ in range(kc)]
        sp = (max(sizes) - min(sizes)) / mean
        if best is None or sp < best[0]:
            best = (sp, dict(zip(names, alloc)))
    return best


def main() -> None:
    macros: list[str] = ["% generated by ceiling.py -- do not edit"]

    def mac(name: str, value) -> None:
        macros.append(f"\\newcommand{{\\{name}}}{{{value}}}")

    mac("chTotalB", f"{TOTAL_B:g}")
    mac("chZips", f"{N_ZIPS:,}".replace(",", "{,}"))
    mac("chReps", N_REPS)
    mac("chRealReps", N_REPS - 1)
    mac("chComponents", len(next(iter(SPLITS.values()))[1]))
    mac("chTargetB", f"{TARGET_B:g}")
    mac("chKAtTarget", int(round(TOTAL_B / TARGET_B)))
    mac("chKPlusOne", int(round(TOTAL_B / TARGET_B)) + 1)
    mac("chSizeAtKPlusOne", f"{1000 * TOTAL_B / (round(TOTAL_B / TARGET_B) + 1):.0f}")
    mac("chBinaries", f"{N_ZIPS * int(round(TOTAL_B / TARGET_B)):,}".replace(",", "{,}"))
    mac("chRepRatio", f"{(N_REPS - 1) / int(round(TOTAL_B / TARGET_B)):.0f}")

    # --------------------------------------------------------------- the ceiling table
    curves: dict[str, list[float]] = {}
    for key, (label, comps) in SPLITS.items():
        Key = key.capitalize()
        mac(f"ch{Key}Label", label)
        mac(f"ch{Key}Split", " / ".join(f"{comps[c]:g}" for c in ("W", "E", "TX", "FL")))
        spreads = []
        for k in KS:
            r = ceiling(comps, k)
            assert r["feasible"], (label, k)
            spreads.append(100.0 * r["ceiling_spread_rel"])
            if k in KS_TABLE:
                mac(f"ch{Key}k{WORD[k]}", f"{100.0 * r['ceiling_spread_rel']:.1f}")
                mac(f"ch{Key}k{WORD[k]}Alloc",
                    "/".join(str(r["districts_per_component"][c])
                             for c in ("W", "E", "TX", "FL")))
                mac(f"ch{Key}k{WORD[k]}Min", f"{r['ceiling_min'] / 1e9:.2f}")
                mac(f"ch{Key}k{WORD[k]}Max", f"{r['ceiling_max'] / 1e9:.2f}")
        curves[key] = spreads
        best_k = KS_TABLE[int(np.argmin([spreads[KS.index(k)] for k in KS_TABLE]))]
        mac(f"ch{Key}BestK", best_k)
        mac(f"ch{Key}BestSpread", f"{spreads[KS.index(best_k)]:.1f}")

    # the one table cell whose spread-minimising budget differs from the log-optimal one
    sp, alloc = min_spread_budget(SPLITS["east"][1], 6)
    mac("chEastkSixMinSpread", f"{100.0 * sp:.1f}")
    mac("chEastkSixMinAlloc", "/".join(str(alloc[c]) for c in ("W", "E", "TX", "FL")))

    # ------------------------------------------------------- saturation arithmetic
    c1, c2 = 1.0 - LAM, THETA * (1.0 - LAM)
    t = SATURATION
    u_own = c1 * t + LAM                    # incumbent holds the whole book at z
    u_other = c2 * t + LAM                  # a candidate with no book at z
    mac("chCone", f"{c1:.2f}")
    mac("chCtwo", f"{c2:.2f}")
    mac("chCgap", f"{c1 - c2:.2f}")
    mac("chSat", f"{100 * t:g}")
    mac("chUown", f"{u_own:.3f}")
    mac("chUother", f"{u_other:.3f}")
    mac("chOppShare", f"{100 * LAM / u_own:.1f}")
    mac("chPremShare", f"{100 * (c1 - c2) * t / u_own:.1f}")
    mac("chUswing", f"{100 * (u_own / u_other - 1):.1f}")

    # ------------------------------------------------- nash vs utilitarian matching
    g = np.array([[100.0, 10.0], [90.0, 1.0]])
    diag = g[0, 0] + g[1, 1]
    anti = g[0, 1] + g[1, 0]
    ldiag = math.log(g[0, 0]) + math.log(g[1, 1] if g[1, 1] > 0 else 1e-300)
    lanti = math.log(g[0, 1]) + math.log(g[1, 0])
    mac("chMatchUtilDiag", f"{diag:.0f}")
    mac("chMatchUtilAnti", f"{anti:.0f}")
    mac("chMatchNashDiag", f"{ldiag:.3f}")
    mac("chMatchNashAnti", f"{lanti:.3f}")

    (HERE / "ceiling_numbers.tex").write_text("\n".join(macros) + "\n")

    # ------------------------------------------------------------------------ figure
    matplotlib.rcParams.update(RC)
    fig, axes = plt.subplots(1, 2, figsize=(10.4, 3.9))
    colors = {"even": PALETTE["A"], "east": PALETTE["B"],
              "coast": PALETTE["neutral"]}

    ax = axes[0]
    for key, (label, _) in SPLITS.items():
        ax.plot(KS, curves[key], marker="o", ms=4.5, lw=1.4, color=colors[key], label=label)
    ax.axvline(TOTAL_B / TARGET_B, color="0.75", lw=1.0, ls=":", zorder=0)
    ax.set_xlabel("number of districts $k$")
    ax.set_ylabel(r"ceiling spread $(\max-\min)/\mathrm{mean}$  [%]")
    ax.set_title("balance ceiling vs. $k$: the best $k$ is a\ncomposition question, not a headcount")
    ax.legend(frameon=False, loc="upper right")
    ax.set_ylim(bottom=0)

    ax = axes[1]
    width = 0.26
    for j, (key, (label, comps)) in enumerate(SPLITS.items()):
        r = ceiling(comps, int(round(TOTAL_B / TARGET_B)))
        sizes = sorted(
            [comps[c] / kc for c, kc in r["districts_per_component"].items()
             for _ in range(kc)])
        xs = np.arange(len(sizes)) + (j - 1) * width
        ax.bar(xs, sizes, width=width * 0.92, color=colors[key], label=label)
    ax.axhline(TARGET_B, color="0.35", lw=1.1, ls="--", zorder=5)
    ax.annotate(f"${TARGET_B:g}B target", xy=(-0.55, TARGET_B),
                xytext=(0, 5), textcoords="offset points", ha="left", fontsize=7.5,
                color="0.25")
    ax.set_xticks(np.arange(int(round(TOTAL_B / TARGET_B))))
    ax.set_xticklabels([str(i + 1) for i in range(int(round(TOTAL_B / TARGET_B)))])
    ax.set_xlabel("district, sorted by ceiling size")
    ax.set_ylabel("ceiling district size  [$B]")
    ax.set_title(f"district sizes at the ceiling, $k={int(round(TOTAL_B / TARGET_B))}$:\n"
                 "the small regions cannot be subdivided")
    ax.legend(frameon=False, loc="upper left", ncol=3, fontsize=7)

    fig.tight_layout(w_pad=4.5)
    overlaps = []
    assert not overlaps, overlaps
    figdir = HERE / "figures"
    figdir.mkdir(exist_ok=True)
    fig.savefig(figdir / "ceiling.png")
    plt.close(fig)

    print("ceiling: " + "; ".join(
        f"{SPLITS[k][0]} " + ", ".join(f"k={kk}:{curves[k][KS.index(kk)]:.1f}%"
                                       for kk in KS_TABLE)
        for k in SPLITS))


if __name__ == "__main__":
    main()
